services:
  db:
    image: postgres:latest
    environment: 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      TZ: "Europe/Moscow"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    env_file:
      - .env
    command: bash -c "alembic upgrade head && python main.py"
    depends_on:
      - db

volumes:
  pgdata:
