[tool.poetry]
name = "schedule-bot-v2"
version = "0.1.0"
description = ""
authors = ["github-main-user <kolya.skripn@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
python-telegram-bot = "^21.9"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
