"""add index to lecture model

Revision ID: dacdc9509f22
Revises: 8793ee61a0bb
Create Date: 2025-04-15 17:31:40.844493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dacdc9509f22'
down_revision: Union[str, None] = '8793ee61a0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lectures_date_time_key', 'lectures', type_='unique')
    op.create_index(op.f('ix_lectures_date_time'), 'lectures', ['date_time'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lectures_date_time'), table_name='lectures')
    op.create_unique_constraint('lectures_date_time_key', 'lectures', ['date_time'])
    # ### end Alembic commands ###
