"""rename lecture datetime column

Revision ID: e827e553a6f6
Revises: 183260a5d8d5
Create Date: 2025-04-24 17:25:12.355654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e827e553a6f6'
down_revision: Union[str, None] = '183260a5d8d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lectures', sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index('ix_lectures_date_time', table_name='lectures')
    op.create_index(op.f('ix_lectures_starts_at'), 'lectures', ['starts_at'], unique=True)
    op.drop_column('lectures', 'date_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lectures', sa.Column('date_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_lectures_starts_at'), table_name='lectures')
    op.create_index('ix_lectures_date_time', 'lectures', ['date_time'], unique=True)
    op.drop_column('lectures', 'starts_at')
    # ### end Alembic commands ###
